services:
  mysqldb:
    image: mysql
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: user_management
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=1234
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55
    networks:
      spring-mysql-net:

  spring_app:
    container_name: spring_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    networks:
      spring-mysql-net:
    # restart: on-failure
    depends_on:
      mysqldb:
        condition: service_healthy

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'
    networks:
      spring-mysql-net:
    depends_on: [mysqldb, spring_app]

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - '3000:3000'
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      spring-mysql-net:
    depends_on: [mysqldb, spring_app, prometheus]

volumes:
  grafana-data:

networks:
  spring-mysql-net:
