# spring-app.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app
  namespace: monitoring-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: spring-app
          image: spring-app:with-apm          # <- Local image name
          imagePullPolicy: Never            # <- Prevent Kubernetes from trying to pull from Docker Hub
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spring-app
  namespace: monitoring-demo
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30080
  selector:
    app: spring-app