# prometheus.yml
global:
  scrape_interval: 30s

scrape_configs:
  - job_name: 'spring-boot-demo'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8081', host.docker.internal:8082]