# spring-alert-rules.yaml
groups:
  - name: spring-app-alerts
    rules:
      - alert: HighCPUUsage
        expr: process_cpu_usage{job="spring-boot"} > 0.8
        for: 30s
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage detected in Spring Boot app"
          description: "CPU usage is above 80% for more than 30 seconds on {{ $labels.instance }}"

      - alert: HttpRequestVolumeHigh
        expr: increase(http_server_requests_seconds_count{job="spring-boot"}[1m]) > 20
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "High HTTP request volume in Spring Boot"
          description: "More than 20 HTTP requests received in the last minute on {{ $labels.instance }}"